### ISSUE TITLE
[Feature Req]Kcptun(go) like preset and commandline

### ISSUE THREAD

**Issue by caoli5288** [liudf0716/xkcptun#2]
THX for your great project. We not care so many parameters. Most time. kcptun's commandline only care about `fast`, `fast2` and etc preset more simply and good. :-)

**Comment by liudf0716** [comment]
yes, that's my target.
In fact, I introduce those parameters from kcptun, in order to support kcptun server-side. but after processing, I found it's very hard to debug with kcptun sever-side, so I implemented myself server-side. there are lots of parameters usesless.
by the end, thanks for your kind suggestion.

**Comment by liudf0716** [comment]
already complete it.
